add_newline = false

format = '''
[┌](bold red)$os$hostname$username$directory$rust$package$git_branch$git_status$time
[└>](bold red)$character'''

[character]
# success_symbol = "[ ](bold green)"
success_symbol = "[ \\$](bold green)"
error_symbol = "[ ](bold red)"

[shell]
style = 'bold yellow'
format = '[$indicator]($style)'
disabled = false

[directory]
format = "[\\[](bold red)[$path]($style)[$read_only]($read_only_style)[\\]](bold red)"
truncation_length = 5
truncation_symbol = "./"
read_only = '  READ ONLY'
style = 'bold italic purple'

[os]
disabled = false
[os.symbols]
Windows = "[\\[](bold red)[](bold blue)[\\]-](bold red)"

[hostname]
format = "[\\[](bold red)$ssh_symbol$hostname[@](bold yellow)"
ssh_only = false
disabled = false
[username]
style_root = 'bold red'
style_user = 'bold cyan'
format = "[$user]($style)[\\]-](bold red)"
disabled = false
show_always = true

[time]
format = ' [[  $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'
style = "bg:#1d2230"
disabled = false
